package org.eclipselabs.bobthebuilder;

enum Feature {
  MISSING_BUILDER,
  MISSING_FIELDS,
  EXTRA_FIELDS,
  MISSING_WITHS,
  MISSING_CONSTRUCTOR,
  MISSING_ASSIGNMENTS,
  MISSING_BUILD, 
  MISSING_VALIDATE,
  MISSING_VALIDATIONS,
  NONE
}